[workspace]
resolver = "2"
members = ["dwata-agents",
    "dwata-api",
    "shared-types"
]
exclude = [
    "gui"
]

[workspace.dependencies]
tokio = { version = "1.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
actix-web = "4"
sqlx = { version = "0.8.1", features = ["runtime-tokio-rustls", "postgres", "chrono", "uuid"] }
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "1.0", features = ["v4", "serde"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
config = "0.14"
anyhow = "1.0"
thiserror = "1.0"
clap = { version = "4.0", features = ["derive"] }
# llm-sdk = { git = "https://github.com/brainless/llm-sdk", branch = "main" }

[workspace.package]
version = "0.5.2"
edition = "2021"
authors = ["dwata"]
license = "GPL-3.0-or-later"
repository = "https://github.com/brainless/dwata"

[profile.dev]
opt-level = 1
incremental = true
codegen-units = 256

[profile.dev.package."*"]
opt-level = 2
