[package]
name = "dwata-desktop"
version = "0.5.3"
description = "Dwata desktop app"
edition = "2021"
license = "GPL-3.0-or-later"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [ "image-ico", "image-png"] }

[features]
prod = ["tauri/custom-protocol"]

[workspace]
